print(Json.parse(5))
print(Json.decode(5, as: Int))
print(Csv.parse(5))
print(File.exists?(5))
print(Console.red(5))
print(Date.parse(5))
print(Http.get(5))
print(Digest.sha256("text"))
print(Json.parse())
print(Json.parse(other: "{}"))
print(Json.encode(1, pretty: 1))
print(Emerald.Json.parse(5))
print(Math.sin(1, 2))
