//! Generates `src/unicode/tables.zig` from the Unicode Character Database.
//!
//! Section 19.1 makes Unicode Emerald's dependency rather than Zig's: the
//! standard library has no grapheme segmentation, normalization, or case
//! mapping, so Emerald vendors the tables it needs with a recorded Unicode
//! version and regenerates them deliberately. This program is that
//! regeneration. It reads the database files `tools/unicode/fetch.sh`
//! downloads and writes the tables to standard output:
//!
//!     bash tools/unicode/fetch.sh 17.0.0 .unicode/17.0.0
//!     zig run tools/unicode/generate.zig -- 17.0.0 .unicode/17.0.0 > src/unicode/tables.zig
//!     zig fmt src/unicode/tables.zig
//!
//! Every table is sorted by code point and read by binary search.

const std = @import("std");

const Range = struct { first: u21, last: u21 };

fn ValuedRange(comptime Value: type) type {
    return struct { first: u21, last: u21, value: Value };
}

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 3) {
        std.debug.print("usage: generate <unicode version> <database directory>\n", .{});
        std.process.exit(64);
    }
    const version = args[1];
    const directory = args[2];

    const read = struct {
        fn file(a: std.mem.Allocator, i: std.Io, dir: []const u8, name: []const u8) ![]const u8 {
            const path = try std.fs.path.join(a, &.{ dir, name });
            return std.Io.Dir.cwd().readFileAlloc(i, path, a, .limited(8 * 1024 * 1024));
        }
    };
    const unicode_data = try read.file(arena, io, directory, "UnicodeData.txt");
    const core = try read.file(arena, io, directory, "DerivedCoreProperties.txt");
    const normalization = try read.file(arena, io, directory, "DerivedNormalizationProps.txt");
    const grapheme = try read.file(arena, io, directory, "GraphemeBreakProperty.txt");
    const emoji = try read.file(arena, io, directory, "emoji-data.txt");
    const properties = try read.file(arena, io, directory, "PropList.txt");
    const special = try read.file(arena, io, directory, "SpecialCasing.txt");

    var buffer: [64 * 1024]u8 = undefined;
    var stdout = std.Io.File.stdout().writerStreaming(io, &buffer);
    const out = &stdout.interface;

    try out.print(
        \\//! Generated by `tools/unicode/generate.zig` from the Unicode Character
        \\//! Database, version {s}. Do not edit; regenerate deliberately, as section
        \\//! 19.1 requires, and run the Unicode conformance tests afterward.
        \\
        \\pub const version = "{s}";
        \\
        \\pub const Range = struct {{ u21, u21 }};
        \\
        \\
    , .{ version, version });

    // Grapheme segmentation (UAX #29).
    try out.writeAll(
        \\pub const GraphemeBreak = enum(u8) {
        \\    other,
        \\    cr,
        \\    lf,
        \\    control,
        \\    extend,
        \\    zwj,
        \\    regional_indicator,
        \\    prepend,
        \\    spacing_mark,
        \\    l,
        \\    v,
        \\    t,
        \\    lv,
        \\    lvt,
        \\};
        \\
        \\
    );
    try writeValued(arena, out, "grapheme_break", "GraphemeBreak", grapheme, null, graphemeBreakName);
    try writeRanges(arena, out, "extended_pictographic", emoji, "Extended_Pictographic");
    try out.writeAll(
        \\/// The Indic_Conjunct_Break property, which rule GB9c reads.
        \\pub const ConjunctBreak = enum(u8) { none, consonant, extend, linker };
        \\
        \\
    );
    try writeValued(arena, out, "conjunct_break", "ConjunctBreak", core, "InCB", conjunctBreakName);

    // Identifiers (UAX #31) and whitespace.
    try writeRanges(arena, out, "xid_start", core, "XID_Start");
    try writeRanges(arena, out, "xid_continue", core, "XID_Continue");
    try writeRanges(arena, out, "white_space", properties, "White_Space");

    // Case mapping, including what Final_Sigma needs.
    try writeRanges(arena, out, "cased", core, "Cased");
    try writeRanges(arena, out, "case_ignorable", core, "Case_Ignorable");

    // Normalization (UAX #15).
    try writeRanges(arena, out, "nfc_quick_check_no", normalization, "NFC_QC; N");
    try writeRanges(arena, out, "nfc_quick_check_maybe", normalization, "NFC_QC; M");

    const records = try parseUnicodeData(arena, unicode_data);
    const exclusions = try collectRanges(arena, normalization, "Full_Composition_Exclusion");
    try writeCombiningClasses(out, records);
    try writeDecompositions(arena, out, records);
    try writeCompositions(out, records, exclusions);
    try writeCaseMappings(arena, out, records, special);

    try out.flush();
}

// Parsing.

const Record = struct {
    code_point: u21,
    combining_class: u8,
    /// A canonical mapping, one level deep; empty when there is none or when
    /// the mapping is a compatibility one.
    decomposition: []const u21,
    upper: ?u21,
    lower: ?u21,
};

fn parseUnicodeData(arena: std.mem.Allocator, text: []const u8) ![]const Record {
    var records: std.ArrayList(Record) = .empty;
    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |line| {
        if (line.len == 0) continue;
        var fields: [15][]const u8 = undefined;
        var parts = std.mem.splitScalar(u8, line, ';');
        for (&fields) |*field| field.* = parts.next() orelse "";

        var decomposition: std.ArrayList(u21) = .empty;
        if (fields[5].len > 0 and fields[5][0] != '<') {
            var codes = std.mem.tokenizeScalar(u8, fields[5], ' ');
            while (codes.next()) |code| try decomposition.append(arena, try parseCode(code));
        }

        try records.append(arena, .{
            .code_point = try parseCode(fields[0]),
            .combining_class = try std.fmt.parseInt(u8, fields[3], 10),
            .decomposition = try decomposition.toOwnedSlice(arena),
            .upper = if (fields[12].len > 0) try parseCode(fields[12]) else null,
            .lower = if (fields[13].len > 0) try parseCode(fields[13]) else null,
        });
    }
    return records.toOwnedSlice(arena);
}

fn parseCode(text: []const u8) !u21 {
    return std.fmt.parseInt(u21, std.mem.trim(u8, text, " "), 16);
}

/// One data line of a property file: its code point range and the fields after
/// it, with the comment removed and each field trimmed.
const Line = struct { range: Range, fields: [3][]const u8, count: usize };

fn parseLine(line: []const u8) !?Line {
    const content = std.mem.trim(u8, if (std.mem.indexOfScalar(u8, line, '#')) |at| line[0..at] else line, " \t\r");
    if (content.len == 0) return null;

    var parts = std.mem.splitScalar(u8, content, ';');
    const codes = std.mem.trim(u8, parts.next().?, " ");
    var range: Range = undefined;
    if (std.mem.indexOf(u8, codes, "..")) |at| {
        range = .{ .first = try parseCode(codes[0..at]), .last = try parseCode(codes[at + 2 ..]) };
    } else {
        const code = try parseCode(codes);
        range = .{ .first = code, .last = code };
    }

    var result: Line = .{ .range = range, .fields = .{ "", "", "" }, .count = 0 };
    while (parts.next()) |part| {
        if (result.count == result.fields.len) break;
        result.fields[result.count] = std.mem.trim(u8, part, " ");
        result.count += 1;
    }
    return result;
}

/// Whether a line's fields match `property`, which is one field such as
/// `XID_Start`, or two joined by `; ` such as `NFC_QC; N`.
fn matches(line: Line, property: []const u8) bool {
    if (std.mem.indexOf(u8, property, "; ")) |at| {
        return line.count >= 2 and std.mem.eql(u8, line.fields[0], property[0..at]) and
            std.mem.eql(u8, line.fields[1], property[at + 2 ..]);
    }
    return line.count >= 1 and std.mem.eql(u8, line.fields[0], property);
}

fn collectRanges(arena: std.mem.Allocator, text: []const u8, property: []const u8) ![]const Range {
    var ranges: std.ArrayList(Range) = .empty;
    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |raw| {
        const line = try parseLine(raw) orelse continue;
        if (matches(line, property)) try ranges.append(arena, line.range);
    }
    return merge(arena, ranges.items);
}

/// Sorts ranges and joins those that touch, which keeps the tables small.
fn merge(arena: std.mem.Allocator, ranges: []Range) ![]const Range {
    std.mem.sort(Range, ranges, {}, struct {
        fn less(_: void, a: Range, b: Range) bool {
            return a.first < b.first;
        }
    }.less);
    var merged: std.ArrayList(Range) = .empty;
    for (ranges) |range| {
        if (merged.items.len > 0 and merged.items[merged.items.len - 1].last + 1 >= range.first) {
            const last = &merged.items[merged.items.len - 1];
            last.last = @max(last.last, range.last);
        } else {
            try merged.append(arena, range);
        }
    }
    return merged.toOwnedSlice(arena);
}

fn contains(ranges: []const Range, code_point: u21) bool {
    var low: usize = 0;
    var high = ranges.len;
    while (low < high) {
        const middle = (low + high) / 2;
        if (code_point < ranges[middle].first) {
            high = middle;
        } else if (code_point > ranges[middle].last) {
            low = middle + 1;
        } else return true;
    }
    return false;
}

// Writing.

fn writeRanges(
    arena: std.mem.Allocator,
    out: *std.Io.Writer,
    name: []const u8,
    text: []const u8,
    property: []const u8,
) !void {
    const ranges = try collectRanges(arena, text, property);
    try out.print("pub const {s} = [_]Range{{\n", .{name});
    for (ranges) |range| try out.print("    .{{ 0x{X:0>4}, 0x{X:0>4} }},\n", .{ range.first, range.last });
    try out.writeAll("};\n\n");
}

/// A property with several values, such as Grapheme_Cluster_Break. `field`
/// selects lines by their first field when the file holds several properties,
/// as DerivedCoreProperties.txt does for InCB.
fn writeValued(
    arena: std.mem.Allocator,
    out: *std.Io.Writer,
    name: []const u8,
    type_name: []const u8,
    text: []const u8,
    field: ?[]const u8,
    comptime valueName: fn ([]const u8) ?[]const u8,
) !void {
    const Entry = ValuedRange([]const u8);
    var entries: std.ArrayList(Entry) = .empty;
    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |raw| {
        const line = try parseLine(raw) orelse continue;
        const value_text = if (field) |wanted| blk: {
            if (line.count < 2 or !std.mem.eql(u8, line.fields[0], wanted)) continue;
            break :blk line.fields[1];
        } else line.fields[0];
        const value = valueName(value_text) orelse continue;
        try entries.append(arena, .{ .first = line.range.first, .last = line.range.last, .value = value });
    }
    std.mem.sort(Entry, entries.items, {}, struct {
        fn less(_: void, a: Entry, b: Entry) bool {
            return a.first < b.first;
        }
    }.less);

    try out.print("pub const {s} = [_]struct {{ u21, u21, {s} }}{{\n", .{ name, type_name });
    for (entries.items) |entry| {
        try out.print("    .{{ 0x{X:0>4}, 0x{X:0>4}, .{s} }},\n", .{ entry.first, entry.last, entry.value });
    }
    try out.writeAll("};\n\n");
}

fn graphemeBreakName(value: []const u8) ?[]const u8 {
    const names = std.StaticStringMap([]const u8).initComptime(.{
        .{ "CR", "cr" },           .{ "LF", "lf" },
        .{ "Control", "control" }, .{ "Extend", "extend" },
        .{ "ZWJ", "zwj" },         .{ "Regional_Indicator", "regional_indicator" },
        .{ "Prepend", "prepend" }, .{ "SpacingMark", "spacing_mark" },
        .{ "L", "l" },             .{ "V", "v" },
        .{ "T", "t" },             .{ "LV", "lv" },
        .{ "LVT", "lvt" },
    });
    return names.get(value);
}

fn conjunctBreakName(value: []const u8) ?[]const u8 {
    const names = std.StaticStringMap([]const u8).initComptime(.{
        .{ "Consonant", "consonant" }, .{ "Extend", "extend" }, .{ "Linker", "linker" },
    });
    return names.get(value);
}

fn writeCombiningClasses(out: *std.Io.Writer, records: []const Record) !void {
    try out.writeAll("/// Nonzero canonical combining classes; every other code point is 0.\n");
    try out.writeAll("pub const combining_class = [_]struct { u21, u21, u8 }{\n");
    var index: usize = 0;
    while (index < records.len) {
        const record = records[index];
        if (record.combining_class == 0) {
            index += 1;
            continue;
        }
        var end = index;
        while (end + 1 < records.len and records[end + 1].code_point == records[end].code_point + 1 and
            records[end + 1].combining_class == record.combining_class) end += 1;
        try out.print("    .{{ 0x{X:0>4}, 0x{X:0>4}, {d} }},\n", .{ record.code_point, records[end].code_point, record.combining_class });
        index = end + 1;
    }
    try out.writeAll("};\n\n");
}

/// Full canonical decompositions, expanded recursively here so the runtime
/// never recurses. Hangul syllables are decomposed algorithmically instead.
fn writeDecompositions(arena: std.mem.Allocator, out: *std.Io.Writer, records: []const Record) !void {
    var mappings: std.AutoHashMapUnmanaged(u21, []const u21) = .empty;
    for (records) |record| {
        if (record.decomposition.len > 0) try mappings.put(arena, record.code_point, record.decomposition);
    }

    var data: std.ArrayList(u21) = .empty;
    try out.writeAll(
        \\/// Each code point with a canonical decomposition, the start of its full
        \\/// decomposition in `decomposition_data`, and its length.
        \\pub const decompositions = [_]struct { u21, u16, u8 }{
        \\
    );
    for (records) |record| {
        if (record.decomposition.len == 0) continue;
        const start = data.items.len;
        try expand(arena, &mappings, record.code_point, &data);
        try out.print("    .{{ 0x{X:0>4}, {d}, {d} }},\n", .{ record.code_point, start, data.items.len - start });
    }
    try out.writeAll("};\n\npub const decomposition_data = [_]u21{\n");
    for (data.items, 0..) |code_point, position| {
        if (position % 8 == 0) try out.writeAll("   ");
        try out.print(" 0x{X:0>4},", .{code_point});
        if (position % 8 == 7) try out.writeAll("\n");
    }
    try out.writeAll("\n};\n\n");
}

fn expand(
    arena: std.mem.Allocator,
    mappings: *const std.AutoHashMapUnmanaged(u21, []const u21),
    code_point: u21,
    into: *std.ArrayList(u21),
) !void {
    const mapping = mappings.get(code_point) orelse return into.append(arena, code_point);
    for (mapping) |part| try expand(arena, mappings, part, into);
}

/// Primary composites: every canonical pair mapping not excluded from
/// composition, sorted by the pair.
fn writeCompositions(out: *std.Io.Writer, records: []const Record, exclusions: []const Range) !void {
    const Pair = struct { first: u21, second: u21, composite: u21 };
    var pairs: [4096]Pair = undefined;
    var count: usize = 0;
    for (records) |record| {
        if (record.decomposition.len != 2) continue;
        if (contains(exclusions, record.code_point)) continue;
        pairs[count] = .{ .first = record.decomposition[0], .second = record.decomposition[1], .composite = record.code_point };
        count += 1;
    }
    std.mem.sort(Pair, pairs[0..count], {}, struct {
        fn less(_: void, a: Pair, b: Pair) bool {
            return if (a.first != b.first) a.first < b.first else a.second < b.second;
        }
    }.less);

    try out.writeAll("/// Canonical pairs and the primary composite each composes to.\n");
    try out.writeAll("pub const compositions = [_]struct { u21, u21, u21 }{\n");
    for (pairs[0..count]) |pair| {
        try out.print("    .{{ 0x{X:0>4}, 0x{X:0>4}, 0x{X:0>4} }},\n", .{ pair.first, pair.second, pair.composite });
    }
    try out.writeAll("};\n\n");
}

/// Simple one-to-one mappings from UnicodeData.txt, and the unconditional
/// one-to-many mappings of SpecialCasing.txt, such as `ß` to `SS`, which take
/// precedence. The conditional ones are language-specific apart from
/// Final_Sigma, which the runtime applies itself.
fn writeCaseMappings(arena: std.mem.Allocator, out: *std.Io.Writer, records: []const Record, special: []const u8) !void {
    for ([_][]const u8{ "lower", "upper" }) |which| {
        try out.print("pub const simple_{s} = [_]struct {{ u21, u21 }}{{\n", .{which});
        for (records) |record| {
            const target = if (which[0] == 'l') record.lower else record.upper;
            if (target) |mapped| try out.print("    .{{ 0x{X:0>4}, 0x{X:0>4} }},\n", .{ record.code_point, mapped });
        }
        try out.writeAll("};\n\n");
    }

    const Special = struct { code_point: u21, lower: []const u21, upper: []const u21 };
    var specials: std.ArrayList(Special) = .empty;
    var lines = std.mem.splitScalar(u8, special, '\n');
    while (lines.next()) |raw| {
        const content = if (std.mem.indexOfScalar(u8, raw, '#')) |at| raw[0..at] else raw;
        var fields: [5][]const u8 = .{ "", "", "", "", "" };
        var parts = std.mem.splitScalar(u8, content, ';');
        var count: usize = 0;
        while (parts.next()) |part| : (count += 1) {
            if (count < fields.len) fields[count] = std.mem.trim(u8, part, " ");
        }
        if (count < 4 or fields[0].len == 0) continue;
        if (fields[4].len > 0) continue; // conditional
        try specials.append(arena, .{
            .code_point = try parseCode(fields[0]),
            .lower = try parseCodes(arena, fields[1]),
            .upper = try parseCodes(arena, fields[3]),
        });
    }
    std.mem.sort(Special, specials.items, {}, struct {
        fn less(_: void, a: Special, b: Special) bool {
            return a.code_point < b.code_point;
        }
    }.less);

    try out.writeAll(
        \\/// Unconditional special casing: the code point, its full lowercase and
        \\/// uppercase mappings, padded with zeros to three code points.
        \\pub const special_casing = [_]struct { u21, [3]u21, [3]u21 }{
        \\
    );
    for (specials.items) |entry| {
        try out.print("    .{{ 0x{X:0>4}, ", .{entry.code_point});
        try writeTriple(out, entry.lower);
        try out.writeAll(", ");
        try writeTriple(out, entry.upper);
        try out.writeAll(" },\n");
    }
    try out.writeAll("};\n");
}

fn parseCodes(arena: std.mem.Allocator, text: []const u8) ![]const u21 {
    var codes: std.ArrayList(u21) = .empty;
    var tokens = std.mem.tokenizeScalar(u8, text, ' ');
    while (tokens.next()) |token| try codes.append(arena, try parseCode(token));
    return codes.toOwnedSlice(arena);
}

fn writeTriple(out: *std.Io.Writer, codes: []const u21) !void {
    try out.writeAll(".{ ");
    for (0..3) |position| {
        if (position > 0) try out.writeAll(", ");
        try out.print("0x{X:0>4}", .{if (position < codes.len) codes[position] else 0});
    }
    try out.writeAll(" }");
}
