#!/usr/bin/env python3
"""Regenerate Emerald's built-in time-zone database (rewrite-context 15.8).

Writes two files under src/tzdata/:

  zones.zlib   every IANA zone's compiled TZif file, each distinct file stored
               once, behind a sorted name index; zlib-compressed
  tzdata.zig   the IANA version and CLDR's Windows-to-IANA zone names

The zone files come from the `tzdata` package on PyPI, which publishes IANA's
releases compiled by `zic`; the Windows names come from CLDR's
windowsZones.xml. By default both are downloaded:

  python3 tools/update-tzdata.py

or read from local copies, for an offline or pinned update:

  python3 tools/update-tzdata.py --wheel tzdata-2026.4-py2.py3-none-any.whl \\
      --windows-zones windowsZones.xml

Only the Python standard library is used. The output depends only on the
inputs, so running it twice gives identical files.

zones.zlib's uncompressed layout, all integers little-endian:

  "EMTZ" u8 format (1)
  u32 zone count, then for each zone in byte order of its name:
      u8 name length, name, u16 index of its file
  u32 file count, then for each file: u32 length, TZif bytes
"""

import argparse
import io
import json
import pathlib
import struct
import sys
import urllib.request
import xml.etree.ElementTree as ElementTree
import zipfile
import zlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "tzdata"
PYPI = "https://pypi.org/pypi/tzdata/json"
CLDR = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml"


def download(url):
    with urllib.request.urlopen(url) as response:
        return response.read()


def latest_wheel():
    release = json.loads(download(PYPI))
    for file in release["urls"]:
        if file["packagetype"] == "bdist_wheel":
            return download(file["url"])
    sys.exit("update-tzdata: PyPI lists no wheel for the latest tzdata release")


def read_wheel(data):
    """The IANA version and a {zone name: TZif bytes} map."""
    with zipfile.ZipFile(io.BytesIO(data)) as wheel:
        version = None
        for line in wheel.read("tzdata/__init__.py").decode().splitlines():
            if line.startswith("IANA_VERSION"):
                version = line.split("=", 1)[1].strip().strip("\"'")
        if version is None:
            sys.exit("update-tzdata: the wheel does not record its IANA version")
        names = [line.strip() for line in wheel.read("tzdata/zones").decode().splitlines() if line.strip()]
        zones = {name: wheel.read("tzdata/zoneinfo/" + name) for name in names}
    for name, data in zones.items():
        if not data.startswith(b"TZif"):
            sys.exit(f"update-tzdata: {name} is not a TZif file")
    return version, zones


def read_windows_zones(data):
    """CLDR's default (territory 001) IANA name for each Windows zone."""
    mapping = {}
    for zone in ElementTree.fromstring(data).iter("mapZone"):
        if zone.get("territory") == "001":
            mapping[zone.get("other")] = zone.get("type")
    return dict(sorted(mapping.items()))


def encode(zones):
    files = []
    index_of = {}
    entries = []
    for name in sorted(zones, key=lambda name: name.encode()):
        data = zones[name]
        if data not in index_of:
            index_of[data] = len(files)
            files.append(data)
        encoded = name.encode()
        if len(encoded) > 255:
            sys.exit(f"update-tzdata: zone name {name} is too long")
        entries.append(struct.pack("<B", len(encoded)) + encoded + struct.pack("<H", index_of[data]))
    out = bytearray(b"EMTZ" + struct.pack("<B", 1))
    out += struct.pack("<I", len(entries)) + b"".join(entries)
    out += struct.pack("<I", len(files))
    for data in files:
        out += struct.pack("<I", len(data)) + data
    return zlib.compress(bytes(out), 9), len(files)


def zig_string(text):
    return json.dumps(text)


def write_zig(version, windows, zones):
    missing = sorted({name for name in windows.values() if name not in zones})
    if missing:
        sys.exit(f"update-tzdata: CLDR names zones the database lacks: {', '.join(missing)}")
    lines = [
        "//! Generated by tools/update-tzdata.py; do not edit by hand. See",
        "//! src/tzdata/README.md for where this data comes from and its terms.",
        "",
        "/// The IANA time zone database release in `zones.zlib`.",
        f"pub const version = {zig_string(version)};",
        "",
        "/// CLDR's default IANA zone for each Windows zone key name.",
        "pub const windows = [_]struct { []const u8, []const u8 }{",
    ]
    lines += [f"    .{{ {zig_string(key)}, {zig_string(name)} }}," for key, name in windows.items()]
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--wheel", type=pathlib.Path, help="a local tzdata wheel instead of PyPI's latest")
    parser.add_argument("--windows-zones", type=pathlib.Path, help="a local CLDR windowsZones.xml instead of CLDR's main branch")
    options = parser.parse_args()

    wheel = options.wheel.read_bytes() if options.wheel else latest_wheel()
    windows_xml = options.windows_zones.read_bytes() if options.windows_zones else download(CLDR)
    version, zones = read_wheel(wheel)
    windows = read_windows_zones(windows_xml)

    compressed, file_count = encode(zones)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / "zones.zlib").write_bytes(compressed)
    (OUTPUT / "tzdata.zig").write_text(write_zig(version, windows, zones))
    print(f"tzdata {version}: {len(zones)} zones in {file_count} files, {len(compressed)} bytes compressed; {len(windows)} Windows names")


if __name__ == "__main__":
    main()
